perplexity:
  model_name: "gpt2"
  max_length: 512
  overlap: 50
  thresholds:
    ppl_max: 25.0
    burstiness_min: 2.5
  device: "cpu"
  language: "en"

stylometry:
  default_baseline: "brown_corpus"
  thresholds:
    warning_z: 2.0
    error_z: 3.0
    ai_confidence_threshold: 0.7
  custom_baselines_dir: "data/baselines/custom_baselines"
  features:
    enabled: ["sentence_length", "ttr", "hapax", "pos_ratios", "punctuation", "function_words"]
    pos_tags: ["NOUN", "VERB", "ADJ", "ADV", "ADP", "DET", "PRON", "CONJ", "NUM", "PART"] 